version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - "/Users/rmorgan/dev/udemy/kube-dock-node/frontend:/app"
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - "/Users/rmorgan/dev/udemy/kube-dock-node/frontend:/app"
    command: ["npm","run","test"]